# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ea376099a3d2fa96807be768cf57e604d0aa29b59432f0546552a186916cb7066ed19a0d8a0323e96fb1634c8185b8144f958cf9ee1005c90f97027b3cc2578

test:
  secret_key_base: 839f828f4f5a5cef850f49f585ca20f929775baf6fc8e855ee85604305d80a0365d8f26adfeb159ab223e5431b0d50d0e268573b5cb9ec0cba5a490d681f2b37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
